/**
 * DBSP Server Protocol
 * ====================
 * 
 * Defines the WebSocket protocol between React clients and the DBSP server.
 * The server runs SQL transformations and streams only the results.
 * 
 * ## Flow
 * 
 * 1. Client connects to DBSP server
 * 2. Client subscribes to views with SQL queries
 * 3. Server processes data and streams results
 * 4. Client receives computed results (no local SQL execution)
 * 
 * ## Benefits
 * 
 * - Heavy computation on server (better for complex queries)
 * - Reduced client memory usage (only results, not source data)
 * - Shared computation across clients (same view = single computation)
 * - Works on low-power devices (tablets, phones)
 */

// ═══════════════════════════════════════════════════════════════════════════════
// CLIENT -> SERVER MESSAGES
// ═══════════════════════════════════════════════════════════════════════════════

/** Subscribe to a view - server will create and stream results */
export interface SubscribeViewMessage {
  type: 'subscribe-view';
  /** Unique view ID (generated by client) */
  viewId: string;
  /** SQL query to execute */
  query: string;
  /** Source names this view depends on (must match server-side sources) */
  sources: string[];
  /** Optional view configuration */
  options?: {
    name?: string;
    joinMode?: 'append-only' | 'full' | 'full-indexed';
    maxRows?: number;
    maxResults?: number;
  };
}

/** Unsubscribe from a view */
export interface UnsubscribeViewMessage {
  type: 'unsubscribe-view';
  viewId: string;
}

/** Request current snapshot of a view */
export interface GetSnapshotMessage {
  type: 'get-snapshot';
  viewId: string;
}

/** Ping for connection health */
export interface PingMessage {
  type: 'ping';
  timestamp: number;
}

export type ClientMessage = 
  | SubscribeViewMessage 
  | UnsubscribeViewMessage 
  | GetSnapshotMessage
  | PingMessage;

// ═══════════════════════════════════════════════════════════════════════════════
// SERVER -> CLIENT MESSAGES
// ═══════════════════════════════════════════════════════════════════════════════

/** Confirmation that subscription was created */
export interface ViewSubscribedMessage {
  type: 'view-subscribed';
  viewId: string;
  /** Names of sources available on server */
  availableSources: string[];
}

/** Full snapshot of view results */
export interface ViewSnapshotMessage {
  type: 'view-snapshot';
  viewId: string;
  results: Record<string, unknown>[];
  count: number;
  stats: ViewStatsMessage;
}

/** Incremental delta update */
export interface ViewDeltaMessage {
  type: 'view-delta';
  viewId: string;
  /** Delta entries: [row, weight] where weight is +1 for insert, -1 for delete */
  delta: Array<[Record<string, unknown>, number]>;
  /** Updated total count */
  count: number;
  /** Updated stats */
  stats: ViewStatsMessage;
}

/** View statistics */
export interface ViewStatsMessage {
  lastUpdateMs: number;
  totalUpdates: number;
  avgUpdateMs: number;
  currentRowCount?: number;
}

/** Error message */
export interface ErrorMessage {
  type: 'error';
  viewId?: string;
  code: 'INVALID_SQL' | 'SOURCE_NOT_FOUND' | 'SUBSCRIPTION_FAILED' | 'INTERNAL_ERROR';
  message: string;
}

/** Pong response */
export interface PongMessage {
  type: 'pong';
  timestamp: number;
  serverTime: number;
}

/** Server info (sent on connection) */
export interface ServerInfoMessage {
  type: 'server-info';
  /** Available source names */
  sources: string[];
  /** Server version */
  version: string;
  /** Number of connected clients */
  clientCount: number;
}

export type ServerMessage = 
  | ViewSubscribedMessage
  | ViewSnapshotMessage 
  | ViewDeltaMessage 
  | ErrorMessage
  | PongMessage
  | ServerInfoMessage;

// ═══════════════════════════════════════════════════════════════════════════════
// SHARED TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/** Configuration for the DBSP server */
export interface DBSPServerConfig {
  /** Port for DBSP server WebSocket */
  port: number;
  /** Data source WebSocket URL (e.g., credit-server) */
  dataSourceUrl: string;
  /** Source configurations - what tables to create from data */
  sources: SourceConfig[];
  /** Enable debug logging */
  debug?: boolean;
}

/** Configuration for a server-side source */
export interface SourceConfig {
  /** Table name (SQL identifier) */
  name: string;
  /** Primary key field(s) */
  key: string | string[];
  /** Which data stream from the data source populates this */
  dataStream: string;
  /** Maximum rows to keep */
  maxRows?: number;
}



